apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-pv
  namespace: {{ .Values.namespace }}
spec:
  storageClassName: {{ .Values.storage.storageClassName }}
  capacity:
    storage: {{ .Values.storage.capacityStorage }}
  accessModes:
    - ReadWriteMany
  nfs:
    server: {{ .Values.storage.fileServer }}
    path: {{ .Values.storage.nfsPath }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
    name: {{ .Release.Name }}-pvc
    namespace: {{ .Values.namespace }}
spec:
    accessModes:
    - ReadWriteMany
    resources:
        requests:
            storage: {{ .Values.storage.requestStorage }}
    storageClassName: {{ .Values.storage.storageClassName }}